### PR TITLE
fixes validation to not allow  have patient with different user 

### LINKED ISSUE #96: Add validation to not allow event_procedure to have patient with different user
e.g.
- if `event_procedure.user != event_procedure.patient.user` event_procudeure must be invalid

### PR DESCRIPTION
**Pull request by lucasleandro1**
Validation of the EventProcedure model to ensure that there is no patient with different user

fix #96

### CODE REVIEW

File: app/models/event_procedure.rb [hunk 1]
```diff
@@ -31,4 +31,15 @@ class EventProcedure < ApplicationRecord
   validates :room_type, presence: true, if: -> { health_insurance? }
   validates :urgency, inclusion: [true, false], if: -> { health_insurance? }
   validates :payment, presence: true
+
+  validate :unique_user
+
+  private
+
+  def unique_user
```
Comment (edimossilva) [inline app/models/event_procedure.rb:39]: find a better name to this ,ethod
```suggestion
  def unique_user
```

**Review by edimossilva — CHANGES_REQUESTED** [review]

File: app/models/event_procedure.rb [hunk 2]
```diff
@@ -32,10 +32,19 @@ class EventProcedure < ApplicationRecord
   validates :urgency, inclusion: [true, false], if: -> { health_insurance? }
   validates :payment, presence: true
 
+  validate :match_patient_event_procedure_user
   validate :custom_and_urgency_cannot_be_true
 
   private
 
+  def match_patient_event_procedure_user
```
Comment (edimossilva) [inline app/models/event_procedure.rb:40]:
```suggestion
  def match_user_with_patient_user
```

File: spec/models/event_procedure_spec.rb [hunk 3]
```diff
@@ -75,6 +71,27 @@
...
+        other_user = create(:user)
+        patient = create(:patient, user: other_user)
+
+        event_procedure = build(:event_procedure, user: user, patient: patient)
+
+        expect(event_procedure).not_to be_valid
+        expect(event_procedure.errors[:base]).to include("The patient must be associated with the same procedure user")
+      end
+
+      it "is valid when has equal user" do
```
Comment (edimossilva) [inline spec/models/event_procedure_spec.rb:87]: This should be inside of a different context

**Review by edimossilva — CHANGES_REQUESTED** [review]

File: app/models/event_procedure.rb [hunk 4]
```diff
@@ -32,10 +32,19 @@ class EventProcedure < ApplicationRecord
...
 
+  validate :match_user_with_patient_user
   validate :custom_and_urgency_cannot_be_true
 
   private
 
+  def match_user_with_patient_user
+    return if patient.nil? || user.nil?
+
+    return unless patient.user_id != user_id
```
Comment (edimossilva) [inline app/models/event_procedure.rb:43]: Avoid using `unless` together with negation 
```suggestion
    return if patient.user_id == user_id
```
